export interface Template {
  slug: string;
  name: string;
  tagline: string;
  stack: string;
  task: string;
  /** Workspace project folder and header label. */
  project: string;
  entryFile: string;
  files: string[];
  /** The instruction or unit the agent writes, used in its step labels. */
  unit: string;
  tests: string[];
  source: string[];
}

export const TEMPLATES: Template[] = [
  {
    slug: "tip-jar",
    name: "Tip jar",
    tagline: "Accept SOL tips with an on-chain total and a public page.",
    stack: "ANCHOR · NEXT.JS",
    task: "Build a tip jar with a send_tip instruction",
    project: "tip-jar",
    entryFile: "programs/tip-jar/src/lib.rs",
    files: [
      "programs/tip-jar/src/lib.rs",
      "programs/tip-jar/Cargo.toml",
      "app/page.tsx",
      "app/wallet.tsx",
      "tests/tip-jar.ts",
      "Anchor.toml",
    ],
    unit: "send_tip instruction",
    tests: [
      "initializes the jar (412ms)",
      "accepts a tip and increments the total (388ms)",
      "rejects a zero amount (204ms)",
    ],
    source: [
      "use anchor_lang::prelude::*;",
      "use anchor_lang::system_program;",
      "",
      'declare_id!("7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU");',
      "",
      "#[program]",
      "pub mod tip_jar {",
      "    use super::*;",
      "",
      "    pub fn send_tip(ctx: Context<SendTip>, amount: u64) -> Result<()> {",
      "        require!(amount > 0, TipError::ZeroAmount);",
      "",
      "        system_program::transfer(",
      "            CpiContext::new(",
      "                ctx.accounts.system_program.to_account_info(),",
      "                system_program::Transfer {",
      "                    from: ctx.accounts.sender.to_account_info(),",
      "                    to: ctx.accounts.jar.to_account_info(),",
      "                },",
      "            ),",
      "            amount,",
      "        )?;",
      "",
      "        let jar = &mut ctx.accounts.jar;",
      "        jar.total = jar.total.checked_add(amount).ok_or(TipError::Overflow)?;",
      "        Ok(())",
      "    }",
      "}",
    ],
  },
  {
    slug: "nft-mint",
    name: "NFT mint page",
    tagline: "A one-page mint for your collection, wallet connect included.",
    stack: "ANCHOR · METAPLEX",
    task: "Build an NFT mint page for a 1,000 piece collection",
    project: "nft-mint",
    entryFile: "programs/nft-mint/src/lib.rs",
    files: [
      "programs/nft-mint/src/lib.rs",
      "programs/nft-mint/Cargo.toml",
      "app/page.tsx",
      "app/mint-button.tsx",
      "tests/nft-mint.ts",
      "Anchor.toml",
    ],
    unit: "mint_one instruction",
    tests: [
      "mints one edition to the buyer (688ms)",
      "increments the minted counter (274ms)",
      "rejects a mint past the supply cap (233ms)",
    ],
    source: [
      "use anchor_lang::prelude::*;",
      "use anchor_spl::token::{self, MintTo, Token};",
      "",
      'declare_id!("4Nd1mBQtrMJVYVfKf2PJy9NZUZdTAsp7D4xWLs4gpsUa");',
      "",
      "#[program]",
      "pub mod nft_mint {",
      "    use super::*;",
      "",
      "    pub fn mint_one(ctx: Context<MintOne>) -> Result<()> {",
      "        let config = &mut ctx.accounts.config;",
      "        require!(config.minted < config.supply, MintError::SoldOut);",
      "",
      "        token::mint_to(",
      "            CpiContext::new_with_signer(",
      "                ctx.accounts.token_program.to_account_info(),",
      "                MintTo {",
      "                    mint: ctx.accounts.mint.to_account_info(),",
      "                    to: ctx.accounts.buyer_ata.to_account_info(),",
      "                    authority: ctx.accounts.config.to_account_info(),",
      "                },",
      "                &[&[b\"config\", &[ctx.bumps.config]]],",
      "            ),",
      "            1,",
      "        )?;",
      "",
      "        config.minted += 1;",
      "        Ok(())",
      "    }",
      "}",
    ],
  },
  {
    slug: "token-gate",
    name: "Token-gated site",
    tagline: "Content that unlocks when the visitor holds your token.",
    stack: "NEXT.JS · DAS",
    task: "Build a site gated by an SPL token balance",
    project: "token-gate",
    entryFile: "app/api/verify/route.ts",
    files: [
      "app/api/verify/route.ts",
      "app/page.tsx",
      "app/gate.tsx",
      "lib/helius.ts",
      "tests/verify.test.ts",
      "package.json",
    ],
    unit: "balance verification route",
    tests: [
      "unlocks for a wallet above the threshold (301ms)",
      "stays locked below the threshold (188ms)",
      "rejects a malformed public key (96ms)",
    ],
    source: [
      'import { NextResponse } from "next/server";',
      'import { getTokenBalance } from "@/lib/helius";',
      "",
      'const MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";',
      "const MIN_BALANCE = 100;",
      "",
      "export async function POST(request: Request) {",
      "  const { owner } = await request.json();",
      "",
      "  if (typeof owner !== \"string\" || owner.length < 32) {",
      '    return NextResponse.json({ error: "Invalid owner" }, { status: 400 });',
      "  }",
      "",
      "  const balance = await getTokenBalance(owner, MINT);",
      "",
      "  return NextResponse.json({",
      "    unlocked: balance >= MIN_BALANCE,",
      "    balance,",
      "  });",
      "}",
    ],
  },
  {
    slug: "usdc-checkout",
    name: "USDC checkout",
    tagline: "Take USDC payments with confirmations you can verify.",
    stack: "NEXT.JS · SPL",
    task: "Build a USDC checkout with payment confirmation",
    project: "usdc-checkout",
    entryFile: "lib/checkout.ts",
    files: [
      "lib/checkout.ts",
      "app/page.tsx",
      "app/pay-button.tsx",
      "app/api/confirm/route.ts",
      "tests/checkout.test.ts",
      "package.json",
    ],
    unit: "transfer builder",
    tests: [
      "builds a transfer for the exact amount (255ms)",
      "creates the recipient token account when missing (410ms)",
      "confirms the signature before returning (302ms)",
    ],
    source: [
      'import { createTransferCheckedInstruction } from "@solana/spl-token";',
      'import { PublicKey, Transaction } from "@solana/web3.js";',
      "",
      'const USDC = new PublicKey("Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr");',
      "const DECIMALS = 6;",
      "",
      "export function buildPayment(",
      "  from: PublicKey,",
      "  to: PublicKey,",
      "  amountUsdc: number,",
      "): Transaction {",
      "  const amount = BigInt(Math.round(amountUsdc * 10 ** DECIMALS));",
      "",
      "  return new Transaction().add(",
      "    createTransferCheckedInstruction(",
      "      from,",
      "      USDC,",
      "      to,",
      "      from,",
      "      amount,",
      "      DECIMALS,",
      "    ),",
      "  );",
      "}",
    ],
  },
];

export const DEFAULT_TEMPLATE = TEMPLATES[0];

export function findTemplate(slug: string | undefined): Template | undefined {
  return TEMPLATES.find((t) => t.slug === slug);
}
